### PR TITLE
Re-enabled multiple version support

### LINKED ISSUE #234: Support different project and server elixir and erlang versions
We have the capability for remote control to use different versions of elixir and erlang than the main server, but it's not presently supported. We need to figure out why this is the case and fix the problem. 

I would like to support elixir 1.13+ and erlang 24+

Areas to investigate: 

- [ ] The releases are built with `include_erts: false`. This means we pick up the erts from the runtime environment, will setting this to `true` fix the issue?
- [ ] Do we need to build on a prior version of elixir + erlang so that the .beam files produced are compatible with earlier versions?

### LINKED ISSUE #267: Fails during install in VS Code
Visual Studio Code on Linux using `asdf`:

elixir          1.14.5-otp-25   /home/mark/.tool-versions
erlang          25.3.2          /home/mark/.tool-versions

Error on startup:
```
Starting lexical release in "/home/mark/.config/Code/User/globalStorage/lexical-lsp.lexical/lexical_install/lexical"
init terminating in do_boot ({load_failed,[gen_server,gen,file_io_server,file,erl_lint,error_logger,code,application_controller,logger_filters,supervisor,proc_lib,lists,logger_config,logger_simple_h,logger_server,logger_backend,kernel,logger,heart,gen_event,file_server,filename,ets,erl_parse,erl_eval,code_server,application_master,application,error_handler]})

Crash dump is being written to: erl_crash.dump...done
[Error - 10:25:48 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:25:48 AM] Connection to server got closed. Server will restart.
true
[Error - 10:25:48 AM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
init terminating in do_boot ({load_failed,[heart,kernel,application_master,application_controller,application,logger_config,logger_server,logger_backend,logger,gen_server,gen_event,gen,file_io_server,file_server,filename,ets,file,error_logger,erl_parse,erl_lint,code_server,erl_eval,code,supervisor,proc_lib,error_handler,lists,logger_simple_h,logger_filters]})

Crash dump is being written to: erl_crash.dump...done
[Error - 10:25:49 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:25:49 AM] Connection to server got closed. Server will restart.
true
[Error - 10:25:49 AM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
init terminating in do_boot ({load_failed,[logger_backend,logger_server,logger_filters,logger,kernel,heart,gen_server,gen_event,gen,file_io_server,file_server,filename,file,ets,error_logger,erl_parse,erl_lint,erl_eval,code_server,code,application_master,application_controller,application,error_handler,supervisor,proc_lib,lists,logger_simple_h,logger_config]})

Crash dump is being written to: erl_crash.dump...done
[Error - 10:25:50 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:25:50 AM] Connection to server got closed. Server will restart.
true
[Error - 10:25:50 AM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:25:50 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
init terminating in do_boot ({load_failed,[logger_filters,supervisor,proc_lib,lists,logger_simple_h,logger_config,logger_backend,logger_server,logger,kernel,heart,gen_server,gen_event,gen,file_io_server,file_server,filename,file,ets,error_logger,erl_parse,erl_lint,erl_eval,code_server,code,application_master,application_controller,application,error_handler]})

Crash dump is being written to: erl_crash.dump...done
[Error - 10:25:51 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:25:51 AM] Connection to server got closed. Server will restart.
true
[Error - 10:25:51 AM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:25:51 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
init terminating in do_boot ({load_failed,[application,supervisor,logger_simple_h,error_handler,logger_config,proc_lib,logger_server,lists,logger_backend,logger_filters,logger,kernel,gen,heart,gen_server,gen_event,file_io_server,file_server,filename,file,ets,error_logger,erl_lint,erl_parse,erl_eval,code_server,code,application_master,application_controller]})

Crash dump is being written to: erl_crash.dump...done
[Error - 10:25:51 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:25:51 AM] The Lexical server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:25:51 AM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:25:51 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

### PR DESCRIPTION
**Pull request by scohen**
Prior to this change, running a project in a different version of elixir or erlang than lexical was compiled under would cause an error.

There were two reasons for this:

 1. The release is extremely sensitive to the version of elixir / erlang, and would not start if they didn't match. This would happen if include_erts is false.
 2. Even if include_erts is true, finding the elixir executable to run would use the inherited environment variables from the server process. ASDF munges the path, and would find the version of elixir that was used to start lexical, not the one the project requests.

The solution is to enable `use_erts` and to undo the path munging that asdf performs. We need to do something similar with rtx.

Fixes #234 
Also fixes #267

### CODE REVIEW

**Comment by scottming** [comment]
May I ask if this version also fixes this issue?

```elixir
~/Code/lexical scott-dev *3 !1 ❯ NAMESPACE=1 mix release lexical --overwrite                          25.3.2.3  1.15.4-otp-25
* assembling lexical-0.1.0 on MIX_ENV=dev
* using config/runtime.exs to configure the release at runtime
* creating _build/dev/rel/lexical/releases/0.1.0/vm.args
* creating _build/dev/rel/lexical/releases/0.1.0/remote.vm.args
* creating _build/dev/rel/lexical/releases/0.1.0/env.sh

08:50:19.832 [error] Task #PID<0.946.0> started from #PID<0.93.0> terminating
** (File.Error) could not change mode for "/Users/scottming/Code/lexical/_build/dev/rel/lexical/erts-13.2.2.2/bin/erl": no such file or directory
    (elixir 1.15.4) lib/file.ex:1776: File.chmod!/2
    (mix 1.15.4) lib/mix/release.ex:800: Mix.Release.copy_erts/1
    (mix 1.15.4) lib/mix/tasks/release.ex:1369: Mix.Tasks.Release.copy/2
    (elixir 1.15.4) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.4) lib/task/supervised.ex:36: Task.Supervised.reply/4
Function: &:erlang.apply/2
    Args: [#Function<0.85066884/1 in Mix.Tasks.Release.assemble/1>, [:erts]]
** (EXIT from #PID<0.93.0>) an exception was raised:
    ** (File.Error) could not change mode for "/Users/scottming/Code/lexical/_build/dev/rel/lexical/erts-13.2.2.2/bin/erl": no such file or directory
        (elixir 1.15.4) lib/file.ex:1776: File.chmod!/2
        (mix 1.15.4) lib/mix/release.ex:800: Mix.Release.copy_erts/1
        (mix 1.15.4) lib/mix/tasks/release.ex:1369: Mix.Tasks.Release.copy/2
        (elixir 1.15.4) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
        (elixir 1.15.4) lib/task/supervised.ex:36: Task.Supervised.reply/4
        ```

**Comment by scohen** [comment]
> May I ask if this version also fixes this issue?

Nope, I have no idea why that's happening; It seems to happen during the `assemble` step in a release, which is out of my hands.

File: apps/remote_control/lib/lexical/remote_control.ex [hunk 1]
```diff
@@ -152,4 +154,38 @@ defmodule Lexical.RemoteControl do
...
+  defp reset_env(:rtx, root_path) do
+    {env, _} = System.cmd("rtx", ~w(), cd: root_path)
+
+    env
+    |> String.trim()
+    |> String.split("\n")
+    |> Enum.map(fn "export " <> key_and_value ->
+      [key, value] =
+        key_and_value
+        |> String.split("=")
```
Comment (Blond11516) [inline apps/remote_control/lib/lexical/remote_control.ex:181]:
```suggestion
        |> String.split("=", parts: 2)
```
This would avoid breaking the pattern match if the value itself contains "="

**Review by Blond11516 — APPROVED** [review]

File: apps/remote_control/lib/lexical/remote_control.ex (hunk 1 above)
Comment (scohen) [reply apps/remote_control/lib/lexical/remote_control.ex:181]: excellent catch.
