### PR TITLE
Convert utf8->latin1 before decoding JSON-RPC payloads

### LINKED ISSUE #287: Unicode diffing bug
I typed

a = "你好

then delete`好`, and append `"`

Then I see an unexpected token error:

CleanShot 2023-07-26 at 22 15 41@2x

This is all the related client log:

```lua
[DEBUG][2023-07-26 22:24:16] .../vim/lsp/rpc.lua:284	"rpc.send"	{
  jsonrpc = "2.0",
  method = "textDocument/didChange",
  params = {
    contentChanges = { {
        range = {
          ["end"] = {
            character = 4,
            line = 16
          },
          start = {
            character = 4,
            line = 16
          }
        },
        rangeLength = 0,
        text = 'a = "你好'
      } },
    textDocument = {
      uri = "file:///Users/scottming/Code/dummy/lib/dummy.ex",
      version = 5
    }
  }
}

[DEBUG][2023-07-26 22:24:54] .../vim/lsp/rpc.lua:284	"rpc.send"	{
  jsonrpc = "2.0",
  method = "textDocument/didChange",
  params = {
    contentChanges = { {
        range = {
          ["end"] = {
            character = 11,
            line = 16
          },
          start = {
            character = 10,
            line = 16
          }
        },
        rangeLength = 1,
        text = ""
      } },
    textDocument = {
      uri = "file:///Users/scottming/Code/dummy/lib/dummy.ex",
      version = 6
    }
  }
}
[DEBUG][2023-07-26 22:24:56] .../vim/lsp/rpc.lua:284	"rpc.send"	{
  jsonrpc = "2.0",
  method = "textDocument/didChange",
  params = {
    contentChanges = { {
        range = {
          ["end"] = {
            character = 10,
            line = 16
          },
          start = {
            character = 10,
            line = 16
          }
        },
        rangeLength = 0,
        text = '"'
      } },
    textDocument = {
      uri = "file:///Users/scottming/Code/dummy/lib/dummy.ex",
      version = 7
    }
  }
}

[DEBUG][2023-07-26 22:24:56] .../vim/lsp/rpc.lua:387	"rpc.receive"	{
  jsonrpc = "2.0",
  method = "textDocument/publishDiagnostics",
  params = {
    diagnostics = { {
        message = 'unexpected token: " " (column 12, code point U+00A0)',
        range = {
          ["end"] = {
            character = 0,
            line = 17
          },
          start = {
            character = 10,
            line = 16
          }
        },
        severity = 1,
        source = "Elixir"
      } },
    uri = "file:///Users/scottming/Code/dummy/lib/dummy.ex"
  }
}
```

### PR DESCRIPTION
**Pull request by zachallaun**
This (hopefully) fixes #287.

I'm not completely sure why this is occurring, but non-ascii characters were seemingly double-encoded, at least on my system (Ubuntu 22.04 via WSL, VS Code desktop on Windows). I've confirmed with `:io.getopts()` right before `IO.read/2` is called that the encoding is set to `:latin1`, but the result after `JsonRpc.decode/1` was that text would be utf8 double-encoded -- that is, it was what you would expect from:

    latin1_data
    |> :unicode.characters_to_binary(:latin1, :utf8)
    |> :unicode.characters_to_binary(:latin1, :utf8)

This would result in `Document.Line` text containing more bytes than it should, which causes text edits to fail, leading behind random extra bytes.

I don't love this "fix" because it feels very much like a band-aid, not addressing whatever the root issue is, but I'd also rather things work in documents containing multi-byte characters.

### CODE REVIEW

**Comment by scottming** [comment]
I tried it and it seems to fix the Chinese encoding issue and it fixes #171  as well:

I can get more people to test it.

**Review by scottming — APPROVED** [review]

File: apps/server/lib/lexical/server/transport/std_io.ex [hunk 1]
```diff
@@ -112,10 +112,16 @@ defmodule Lexical.Server.Transport.StdIO do
     end
   end
 
-  defp read(device, amount) do
+  defp read_body(device, amount) do
     case IO.read(device, amount) do
-      data when is_binary(data) or is_list(data) -> {:ok, data}
-      other -> other
+      data when is_binary(data) or is_list(data) ->
+        # This is a bit "magical" and is likely a symptom of a bug elsewhere.
```
Comment (scohen) [inline apps/server/lib/lexical/server/transport/std_io.ex:118]: I take slight issue with this comment. This is the lowest level of lexical. If the bug is elsewhere, where is it? You established that the binaries decoded here were not
Utf8.  Where else would the bug be?

Comment (zachallaun) [reply apps/server/lib/lexical/server/transport/std_io.ex:118]: "Bug" may be the wrong word -- "misunderstanding" is probably more accurate.

How about:

```elixir
# Ensure that incoming data is latin1 to prevent double-encoding to utf8 later
```

Comment (zachallaun) [reply apps/server/lib/lexical/server/transport/std_io.ex:118]:
```suggestion
        # Ensure that incoming data is latin1 to prevent double-encoding to utf8 later
```
